In [405]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, log_loss
from torchsummary import summary
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
import matplotlib.pyplot as plt

In [406]:
df = pd.read_csv('Sonar.csv')
df

V1      V2      V3      V4      V5      V6      V7      V8      V9  \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

        V10  ...     V52     V53     V54     V55     V56     V57     V58  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

        V59     V60  Class  
0    0.0090  0.0032      R  
1    0.0052  0.0044      R  
2    0.0095  0.0078      R  
3    0.0040  0.0117      R  
4    0.0107  0.0094      R  
..      ...     ...    ...  
203  0.0193  0.0157      M  
204  0.0062  0.0067      M  
205  0.0077  0.0031      M  
206  0.0036  0.0048      M  
207  0.0061  0.0115      M  

[208 rows x 61 columns]

In [407]:
lb = LabelEncoder()
y= lb.fit_transform(df['Class'])
X = df.drop('Class' , axis = 1)
X.shape

(208, 60)

In [408]:
X_train, X_test, y_train, y_test = train_test_split(X.values, y, test_size = 0.3, 
                                                    random_state=24)

In [409]:
X_torch = torch.from_numpy(X_train)
y_torch = torch.from_numpy(y_train)

In [410]:
print(X_torch.size())
print(y_torch.size())

torch.Size([145, 60])
torch.Size([145])


In [411]:
## Activation Functions 
#tanh()
#ReLU
#SeLU
#etc

In [412]:
torch.manual_seed(24)
model = nn.Sequential(nn.Linear(in_features=X_train.shape[1], out_features=50),
                      nn.ReLU(),
                     nn.Linear(in_features=50 , out_features=30),
                    nn.Tanh(),
                     nn.Linear(in_features=30 , out_features=10),
                     nn.Tanh(),
                     nn.Linear(in_features=10 , out_features=1),
                    nn.Tanh())

In [413]:
summary(model, (1,X_train.shape[1]))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                [-1, 1, 50]           3,050
              ReLU-2                [-1, 1, 50]               0
            Linear-3                [-1, 1, 30]           1,530
              Tanh-4                [-1, 1, 30]               0
            Linear-5                [-1, 1, 10]             310
              Tanh-6                [-1, 1, 10]               0
            Linear-7                 [-1, 1, 1]              11
              Tanh-8                 [-1, 1, 1]               0
Total params: 4,901
Trainable params: 4,901
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.02
Estimated Total Size (MB): 0.02
----------------------------------------------------------------


In [445]:
criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.8)
# with different optimizer
# optimizer = torch.optim.SGD(model.parameters(), lr = 0.8 , momentum=0.2)
#With Nesterov Optimizer
# optimizer = torch.optim.Adagrad(model.parameters(), lr = 0.8)
# optimizer = torch.optim.RMSprop(model.parameters(), lr = 0.8)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.8
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [415]:
for p in model.parameters():
    print(p)

y_pred = model(X_torch.float())
y_pred[:3]

Parameter containing:
tensor([[ 0.0683, -0.0323, -0.1097,  ..., -0.0454, -0.0550,  0.1005],
        [-0.0196, -0.0788,  0.0382,  ..., -0.0942,  0.0762,  0.0440],
        [-0.0940, -0.0112, -0.0840,  ...,  0.0035, -0.1179, -0.0636],
        ...,
        [-0.1260,  0.1086, -0.0067,  ...,  0.1088, -0.0604, -0.0645],
        [-0.0705,  0.0279, -0.0343,  ...,  0.1208, -0.0642, -0.0883],
        [-0.0680,  0.0611,  0.0285,  ...,  0.1239, -0.0421,  0.0881]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0725, -0.0626, -0.0104, -0.0377,  0.0466,  0.1280,  0.0422,  0.0255,
        -0.0523,  0.0709,  0.0221,  0.0605, -0.0020,  0.0753, -0.0296,  0.0739,
        -0.0783, -0.0337, -0.0692, -0.0181,  0.0145,  0.0352, -0.0108,  0.0654,
        -0.0298,  0.0159,  0.1283, -0.0239,  0.1012,  0.0757,  0.0678, -0.0467,
        -0.0158, -0.0765, -0.0143, -0.0786,  0.0180,  0.0700,  0.0247, -0.0434,
         0.0558, -0.0637, -0.0371,  0.0404, -0.0740,  0.1002,  0.1094, -0.0509,
         0.1003

tensor([[0.2367],
        [0.2404],
        [0.2503]], grad_fn=<SliceBackward0>)

In [416]:
y_torch = y_torch.unsqueeze(1)
print(y_torch.shape)
print(y_pred.shape)

torch.Size([145, 1])
torch.Size([145, 1])


In [417]:
for epoch in np.arange(0,1000):
       # Forward pass: Compute predicted y by passing x to the model
       y_pred_prob = model(X_torch.float())

       # Compute and print loss
       loss = criterion(y_pred_prob, y_torch.float())
       if epoch%100 == 0:
          print('epoch: ', epoch+1,' loss: ', loss.item())

       # Zero gradients, perform a backward pass, and update the weights.
       optimizer.zero_grad()

       # perform a backward pass (backpropagation)
       loss.backward()

       # Update the parameters
       optimizer.step()
#print('epoch: ', epoch+1,' loss: ', loss.item())

epoch:  1  loss:  0.695387065410614
epoch:  101  loss:  0.7960202693939209
epoch:  201  loss:  0.7960202693939209
epoch:  301  loss:  0.7960202693939209
epoch:  401  loss:  0.7960202693939209
epoch:  501  loss:  0.7960202693939209
epoch:  601  loss:  0.7960202693939209
epoch:  701  loss:  0.7960202693939209
epoch:  801  loss:  0.7960202693939209
epoch:  901  loss:  0.7960202693939209


In [418]:
X_torch_test = torch.from_numpy(X_test)

### Inferencing on test set
lin_output = model(X_torch_test.float()) # Equivalent predict_proba / predict

np_out = lin_output.detach().numpy()
y_pred_prob = 1 / (1 + np.exp(-np_out))

In [419]:
y_pred_prob = y_pred_prob.reshape(y_test.shape[0],) 

y_pred = np.where(y_pred_prob >= 0.5,1,0)

## Test Set Accuracy Score
print(accuracy_score(y_test,y_pred))

log_loss(y_test, y_pred_prob)

0.3492063492063492


0.9640553750861154

In [420]:
y_test.shape

(63,)

In [421]:
y_pred.shape

(63,)

In [422]:
X_torch_test.shape

torch.Size([63, 60])

In [423]:
X_train.shape

(145, 60)